services:
  - type: web
    name: decompiler-explorer
    env: docker
    plan: standard
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: decompiler_explorer.settings.docker
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        fromDatabase:
          name: dce-postgres
          property: connectionString
      - key: MEMCACHED_HOST
        fromService:
          type: pserv
          name: dce-memcached
          property: host
      - key: MEMCACHED_PORT
        value: 11211
      - key: WORKER_AUTH_TOKEN
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DJANGO_DEBUG
        value: "False"
    healthCheckPath: /api/decompilers/

  - type: pserv
    name: dce-memcached
    env: image
    image:
      url: memcached:1.6-alpine
    autoDeploy: true
    plan: starter
    startCommand: memcached -m 64 -p 11211 -u memcache -l 0.0.0.0

databases:
  - name: dce-postgres
    databaseName: dce
    plan: standard
    user: dce